### ISSUE TITLE
Offer Dark Mode Version of Graphs & Charts

### ISSUE THREAD

**Issue by crimelabs786** [urk-stav/leetcode-compensation#1]
Hi @urk-stav, glad to see someone working on this. Projects like these, really help dealing with _information asymmetry_ in our industry.

I'd personally want to see some dark mode version of these datasets. For users who have dark mode set-up, it can amount to being met with a flash-of-blinding-light, when navigating through a page, and be met with content against pure white background.

The opposite isn't true. As in, for readers that prefer light mode, being met with dark mode content (white-ish foreground, darker shade of background) won't be as jarring.

Would you be interested in publishing this as GitHub pages? If so, you might want to use Python MkDocs Material, and see if you can offer dark mode images for users who want dark mode, and light mode images for users who want light mode. For reference, check homepage of SimpleAnalytics.

Happy to help with PR, if you need.

**Comment by kuutsav** [comment]
Thanks for suggestions. Your argument is valid.
I'll add the plots in dark mode as well.
Will let you know if I need any help later.

**Comment by urk-stav** [comment]
Done!
